Repository Girlscript-WOB/Open-source-Practice, pull requests merged in 2024-09, with the labels that each got.

#10 Added [Meet Jain | Mentor]
  Mentors/Readme.md
Labels: Mentor

#11 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#12 Update README.md
  README.md
Labels: enhancement

#13 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#14 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#17 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#18 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#19 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#20 added shivam as mentor
  Mentors/Readme.md
Labels: Mentor

#22 Update README.md
  README.md
Labels: enhancement

#23 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#25 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#26 add: updated readme with rohitroy-dev
  Mentors/Readme.md
Labels: Mentor

#28 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#29 Update Mentor profile - Akshit Batra
  Mentors/Readme.md
Labels: Mentor

#31 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#32 update
  Campus Ambassador/Readme.md
Labels: CA

#33 Update Readme.md - Parth Madhvani
  Mentors/Readme.md
Labels: Mentor

#35 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#36 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#37 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#39 Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#40 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#38 Update Readme.md
  Campus Ambassador/Readme.md
Labels: CA

#34 Update Readme.md
  Campus Ambassador/Readme.md
Labels: Change requested, CA

#43 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#42 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#41 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#44 dhanushHM26
  Mentors/Readme.md
Labels: Mentor

#45 Update Readme.md - Asmita Mishra
  Mentors/Readme.md
Labels: Mentor

#46 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#47 Update Readme.md
  Mentors/Readme.md
Labels: Mentor

#51 Updated Readme
  Mentors/Readme.md
Labels: Mentor
